import "./setup.test";
import "./root/root.test";
import "./user/registration.test";
import "./auth.test";
import "./user/read.test";
import "./user/mutation.test";
import "./quiz/creation.test";
import "./submission/creation.test";
import "./user/deletion.test";
